export const GET_ALL_MEMES_REQUEST = 'GET_ALL_MEMES_REQUEST';
export const GET_ALL_MEMES_SUCCESS = 'GET_ALL_MEMES_SUCCESS';
export const GET_ALL_MEMES_FAILED = 'GET_ALL_MEMES_FAILED';

export const CREATE_MEME_REQUEST = 'CREATE_MEME_REQUEST';
export const CREATE_MEME_SUCCESS = 'CREATE_MEME_SUCCESS';
export const CREATE_MEME_FAILED = 'CREATE_MEME_FAILED';

export const DELETE_MEME_SUCCESS = 'DELETE_MEME_SUCCESS';
export const DELETE_MEME_FAILED = 'DELETE_MEME_FAILED';
